### ISSUE TITLE
cannot login

### ISSUE THREAD

**Issue by githubfanster** [auth0-blog/blazor-interactive-auto#3]
Hello!

I downloaded the code zip into my Windows 11 machine, added my domain and clientid, then ran the app
i got the universal login page asking me to login to my dev domain using email and password (the Welcome message is correct)

the email and password i entered are the same ones i use to login to my auth0 dashboard (the data center is in japan because i'm in southeast asia) but for some reason those credentials are not accepted in the universal login page that shows up when i run the app in debug mode.

i'm using Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.9.5, and tested with both Firefox and Google Chrome browsers.

any suggestion on what to do next to perhaps troubleshoot?

**Comment by andychiare** [comment]
Hi @githubfanster, you must create a new user and log in with the user's credentials.
You can do it from the [Auth0 dashboard](https://auth0.com/docs/manage-users/user-accounts/create-users) or through the signup link in the Universal Login page.

Your account to access your Auth0 dashboard is NOT a tenant user, i.e., is NOT a user of your applications.

**Comment by githubfanster** [comment]
thanks! problem solved :-)
